#!/bin/bash

if [ -e /etc/iegor_router/state ]; then
	check=$(cat /etc/iegor_router/state)
	if [ "$check" = "1" ]; then
		#/etc/iegor_router/router.stop
		systemctl restart iegor_router
		echo 0 > /etc/iegor_router/state
	fi
else
	echo "file state not found"
fi
